### ISSUE TITLE
Error Using OpenAI API Key - https://attackgen.streamlit.app/

### ISSUE THREAD

**Issue by OrlandoMD** [mrwadams/attackgen#10]
Hello- What a neat project! I'm attempting to exercise the AttackGen instance hosted at https://attackgen.streamlit.app/ 

**Screenshot 01:** On the Welcome page, I paste a freshly created OpenAI API key from my ChatGPT Pro account, press enter for acceptance, and make additional sections.

**Screenshot 02:** On the Generate Threat Group Scenario page, I click "Generate Scenario.

**Screenshot 03:**  The Generate Threat Group Scenario page then presents the following error:
"An error occurred while generating the scenario: Error code: 404 - {'error': {'message': 'The model gpt-4 does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}"

**Screenshot 04:** Returning to the Welcome page, the API field is cleared.  

Entering the same API key or a newly created one leads to the same results and error message.  

Could you please review and advise if something is not working or how I should change my approach to exercising this AttackGen instance?

Respectfully,

Orlando Stevenson

![01_Welcome Screen - 2024-04-11 23_15_41-](https://github.com/mrwadams/attackgen/assets/18099390/0f92b81b-2c2b-4d5c-b900-d3757e0e6fc9)
![02_Generate Threat Group Scenario- 2024-04-11 23_15_41-](https://github.com/mrwadams/attackgen/assets/18099390/7698a509-b8e8-4e1d-8da5-ba01003d428b)
![03_Generate Threat Group Scenario- Error Code 404 _ 2024-04-11 23_15_41-](https://github.com/mrwadams/attackgen/assets/18099390/9f736d64-1b14-44ba-bc9a-8ceb9fad2dce)
![04_Welcome Screen - Missing OpenAI API Key _2024-04-11 23_15_41-](https://github.com/mrwadams/attackgen/assets/18099390/6599ddc3-af34-4926-8384-f9ce1ce4466f)

**Comment by mrwadams** [comment]
Hi @OrlandoMD,

Thanks for looking at the project. I believe this issue is caused because you don't have a payment method associated with your OpenAI account, or have insufficient credit in your account to use the API.

Please try adding a payment method then generating a fresh API key after a few minutes.

Thanks,

Matt

**Comment by OrlandoMD** [comment]
Hi Matt,

Update - while I have a paid ChatGPT personal subscription, I dug deeper.  As you point out the OpenAI API requires its own payment method to be established as shown in screenshots that follow.  My first generated scenario cost $0.06 after deposting $10.. not bad.  
Thank you!
Orlando Stevenson
![01_OpenAI - API Billing Setup_2024-04-12_11-15-28](https://github.com/mrwadams/attackgen/assets/18099390/5a45653f-db03-497f-8fc5-e230e2167230)
![02_AttackGen Successful Run_2024-04-12_11-15-28](https://github.com/mrwadams/attackgen/assets/18099390/109e1bdc-2df1-4d86-9631-a19bc8227ac2)
