### ISSUE TITLE
Suggestion: rename Welcome.py

### ISSUE THREAD

**Issue by bjcbusiness** [mrwadams/attackgen#13]
The little hand-wavy-thing at the beginning of the file name _Welcome.py is a PITA when it comes to the command line. Would you consider renaming it just "Welcome.py"?

**Comment by cypheroxide** [comment]
> The little hand-wavy-thing at the beginning of the file name _Welcome.py is a PITA when it comes to the command line. Would you consider renaming it just "Welcome.py"?

A pull request has been submitted for this issue.  It is now on the project maintainer's timeline.

**Comment by mrwadams** [comment]
Resolved by #16.
