### ISSUE TITLE
Scenario Generation Error: 'ascii' codec can't encode character '\xa3' - Possible Encoding Issue

### ISSUE THREAD

**Issue by 0xhav0c** [mrwadams/attackgen#5]
Hello, firstly i want to thank u for this tool. It's amazing. I have one issue about "Generate Scenario". When i try the this function get  a fail. Fail output like that: 

![image](https://github.com/mrwadams/attackgen/assets/96983443/fda841e9-a824-423c-9c9b-6256d2f56f1b)

UI Output
`An error occurred while generating the scenario: 'ascii' codec can't encode character '\xa3' in position 16: ordinal not in range(128)`

Console output
/app/pages/1_🛡️_Threat_Group_Scenarios.py:198: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=1) if len(x) > 0 else None)
/app/pages/1_🛡️_Threat_Group_Scenarios.py:198: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=1) if len(x) > 0 else None)
/usr/local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI
  warn_deprecated(`

Thanks in advance for your help

**Comment by mrwadams** [comment]
Hi @0xhav0c,

Glad you like the tool.

I'm aware of the Pandas deprecation warning and have just fixed the `langchain_community.chat_models.openai.ChatOpenAI` warning in https://github.com/mrwadams/attackgen/commit/89dd937362d601feb407d4341587696ae152990e

Could you please confirm if you're using the version of the tool hosted at https://attackgen.streamlit.app, or are you cloning the repo and running the Streamlit app locally?

Thanks,

Matt

**Comment by 0xhav0c** [comment]
I installed latest build today. Same issue still continue. By the way, same issue on https://attackgen.streamlit.app/

![image](https://github.com/mrwadams/attackgen/assets/96983443/a871f78f-86eb-4f2f-81b6-210badebd736)

Thanks a lot

**Comment by mrwadams** [comment]
Hi @0xhav0c,

Thanks for continuing to test the tool. It looks like you're generating a Threat Group Scenario. Could you please tell me which threat actor group you're selecting so I can try and replicate the issue?

Thanks,

Matt

**Comment by 0xhav0c** [comment]
Hello @mrwadams 

First of all, you're welcome, with pleasure. Frankly, I experience this problem in all threat actor groups. I tried it in "gpt-4-turbo-preview", "gpt-4" and "gpt-3.5-turbo" versions. I even chose 5-6 models on the "Select your company's industry" side. I'm getting the same error.

Thanks

**Comment by mrwadams** [comment]
That's interesting, and it makes me think that you might have some browser settings or a specific configuration that affect how your browser is interpreting or rendering certain characters. For example, the browser's character encoding settings or language preferences could be influencing how the response from the model is displayed.

Could you try using AttackGen from a different browser or machine to see if you still get the same error?

**Comment by 0xhav0c** [comment]
Chrome MacOS

![image](https://github.com/mrwadams/attackgen/assets/96983443/cc1c7e45-7127-460e-9912-5a7aa615f352)

Safari MacOS
![image](https://github.com/mrwadams/attackgen/assets/96983443/38877876-af0e-48e0-9b95-e5029b382c41)

Can u share with me about create a Threat Group Scenarios with step by step. Maybe i made i mistake when i try to usage.

**Comment by mrwadams** [comment]
It's really straightforward, so I don't think you could be making a mistake when trying to generate a scenario. Here's a quick walkthrough of me generating a Threat Group Scenario. I was using Safari on MacOS when recording the video (about 10 minutes ago).

https://www.canva.com/design/DAGBFtXSoQU/FpGfF5jDaG_Xu8SXUuuKVw/watch?utm_content=DAGBFtXSoQU&utm_campaign=designshare&utm_medium=link&utm_source=editor

One thing I noticed in your screenshots is that you seem to have Google Translate running? Could you try disabling all browser / plugins extensions and then testing again?

**Comment by 0xhav0c** [comment]
Thank you for sharing the steps with me. After removing the plugins and trying again, I got the same error. When I installed Opera and tried it through Opera, I got the same error again.

I checked my API key. When I enter any different random API key, another error occurs. It has nothing to do with my fault. I'm wondering what the problem could be. I've never encountered a bug like this before. Have you set any ".env" configuration for Attackgen on your device? I can't think of anything else.

You can watch the error I get with Opera from the [Video Link](https://video-private-assets.canva.com/VAGBF2V-6a0/v/366f99965f.mp4?exp=1711906380000&cf-ck=M7k80ox_kqa9r5SVYbj5YT11-TTSh18359WYBJzBLtc&cf-sig=Wl2kvBhMCYPXrOUxtoFQ4YECUFSd7dO_Wbq8_Fs2VkE&cf-sig-kid=CO7cCjZ_YiI=&sig=AoP1TCrBc_eJU1t5zQKEYxZeaVeVcdv8_-kG7GuxHe0&sig-kid=GzFgFdhXD-Q=).

**Comment by 0xhav0c** [comment]
Hi again @mrwadams 

I found the problem. This error occurs if characters such as "£" are given in the API key. I solved the problem by regenerating the API key. Thank you very much.

**Comment by mrwadams** [comment]
Glad you managed to resolve it! Which model provider were / are you using?
