### ISSUE TITLE
how to support local ollama?

### ISSUE THREAD

**Issue by langyajiekou** [mrwadams/attackgen#6]
how to support local ollama?

**Comment by mrwadams** [comment]
Thanks for the suggestion, that would be a great feature. 

Give me a couple of days... 🙂

**Comment by mrwadams** [comment]
I've now added support for local models that are accessible via the API endpoint that Ollama exposes. Please test it out and let me know if you run into any issues.

The quality of the outputs is of course highly dependent on the capability of the local model, but I've tested Mistral 7B and Gemma and both generated reasonable scenarios.
