### ISSUE TITLE
Error generating a scenario

### ISSUE THREAD

**Issue by gen973** [mrwadams/attackgen#7]
Hello. I'm sure it's something simple and that I'm just being clumsy, but I've tried on the website and by cloning the repository locally, and when I generate a scenario, I get the following error message:
An error occurred while generating the scenario: Error code: 404 - {'error': {'message': 'The model gpt-4-turbo-preview does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Thank you in advance.

**Comment by mrwadams** [comment]
Hi @gen973,

I've tested this today via the version hosted on Streamlit Community Cloud and can't replicate the error. 

Please try regenerating a new OpenAI API key and using that. If that doesn't work, I suggest you contact OpenAI support.

Closing this as I don't believe it's an AttackGen-specific issue.

Thanks,

Matt

**Comment by gen973** [comment]
Thank you for your answers.
I´ve resolved the problema adding payment method in https://platform.openai.com/account/billing/overview.
Best regards
