### ISSUE TITLE
langsmith not disable-able

### ISSUE THREAD

**Issue by bjcbusiness** [mrwadams/attackgen#8]
I want to use attackgen but do not have a langchain API key. This projects documentation indicates 
"If you do not wish to use LangSmith, you can delete the LangSmith related environment variables from the top of the following files"

I commented out the environment variables portion in those files. I tried all 4 environment variables, then just the last one (API_KEY) but receive the same failure:

```
File "/home/bbb/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "/.../attackgen/attackgen/pages/1_🛡️_Threat_Group_Scenarios.py", line 28, in <module>
    client = Client()
             ^^^^^^^^
File "/home/bbb/venv/lib/python3.11/site-packages/langsmith/client.py", line 480, in __init__
    _validate_api_key_if_hosted(self.api_url, self.api_key)
File "/home/bbb/venv/lib/python3.11/site-packages/langsmith/client.py", line 269, in _validate_api_key_if_hosted
    raise ls_utils.LangSmithUserError(
```

**Comment by mrwadams** [comment]
Setting a LangChain API key is now optional when generating either a Threat Group Scenario or Custom Scenario. If an API key is not set in the secrets.toml file then a info message is displayed to let user know that the run won't be logged in LangSmith.

**Comment by bjcbusiness** [comment]
Alas, it doesn't seem to be fully fixed. I copied the secrets example file and successfully got the "threat scenario" page to load, but when I click "generate scenario" I receive the error,
```
An error occurred: API key must be provided when using hosted LangSmith API
```

Is my assumption correct that this utility should work without an API Key? I have an openazure key for the main LLM but do not want to procure additional keys for other functions.

Thank you

**Comment by mrwadams** [comment]
I might need to update the instructions / example secrets file to make
things a bit clearer.

If you use a completely blank secrets file then it should work.

**Comment by bjcbusiness** [comment]
I have cleared out ~/.streamlit/secrets.toml and receive the same error

**Comment by mrwadams** [comment]
Thanks for continuing to test this @bjcbusiness. Please clone the repo again and let me know how you get on.

**Comment by bjcbusiness** [comment]
Thanks @mrwadams -- seems to work now!
